language: python
cache: pip
python:
  - "3.6"
before_install:
  - python3 -m pip install -U coverage codecov mypy==0.471
  - python3 -m pip install test-requirements.txt
install:
  - python3 -m pip install -r requirements.txt
script:
  - python3 -m coverage run --branch -m unittest discover -t . -s ni/test/
  - ./mypy.sh
after_success:
  - codecov
